name: 'Go Grade Action'
description: 'Run `go test` with grading considerations and rich summary output & annotations'

inputs:
  testArguments:
    description: 'Arguments to `go test`, `-json` will be prepended'
    required: false
    default: './...'
  rubricUrl:
    description: 'Where to fetch the rubric JSON from'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
